version: '3.4'

services:
  08nasaproject:
    image: 08nasaproject
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
